sonar.projectKey=Gabriel-Souza18_Alarm_Map
sonar.organization=gabriel-souza18

# Configurações de código, testes e relatórios de cobertura JaCoCo
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

